---

- hosts: all
  become: true
  tasks:

  - name: Synchronization using rsync protocol (push)
    ansible.posix.synchronize:
      src: /home/pi/Multi_Camera_System_APTITUDE/
      dest: pi@192.168.1.27:/home/pi/test_ansible
